### ISSUE TITLE
Option to disallow duplicate keys in input

### ISSUE THREAD

**Issue by danielnorberg** [hjson/hjson-java#5]
It'd be useful to be able to configure the parser to fail on duplicate keys in input in order to catch user errors in e.g. configuration files.

I.e. fail on:

``` yaml
some_config: {
  param1: foo
  param2: bar
  param2: baz  # Really intended to set param3 here but made a copypasta mistake
}
```

What do you think?
